language: python
python:
  - "2.7"
  - "3.5"
  - "3.6"
env:
  - SPHINX_VERSION=1.3.6
  - SPHINX_VERSION=1.4.6
  - SPHINX_VERSION=1.5.6
  - SPHINX_VERSION=1.6.1
  - SPHINX_VERSION=1.6.2
  - SPHINX_VERSION=1.6.3
  - SPHINX_VERSION=""
install:
  - pip install coveralls
  # install sphinx
  - if [[ $SPHINX_VERSION != "" ]]; then
        pip install sphinx==${SPHINX_VERSION};
    else
        pip install sphinx;
    fi
  - pip install sphinx-testing
  - python setup.py install

script:
  - coverage run --source=autodocsumm setup.py pytest

after_success:
  coveralls
